# Generated by Django 2.2.7 on 2019-11-04 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acticles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Articles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('content', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='Acticles',
        ),
    ]
